---
name: Release

on:
  push:
    branches:
      - main
      - release-*

jobs:
  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'release: ')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run gotagger
        env:
          RELEASE_DRY_RUN: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make release
